import React, { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "@/components/footer";
import Link from "next/link";

export default function Storeis() {

    return (
        <>
            <Head>
                <title>Storeis - Urban Fits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Navbar />
            <main className='w-full bg-white flex justify-center lg:justify-end transition-all ease-linear duration-500' >
                <section className="w-full layout_height flex flex-col justify-center items-center gap-y-5 transition-all ease-linear duration-500 overflow-hidden" >
                    <h2 className="text-3xl font_gotham_medium tracking-expand">STORIES PAGE</h2>
                </section>
            </main>
            <Footer />
        </>
    );
}
